!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS) /DNOMINMAX /D_USE_MATH_DEFINES

all: "$(OUTDIR)\FSM PhatMan.dll" "$(OUTDIR)\FSM PhatMan.prs"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\FSM PhatMan.dll": $(OUTDIR)\PhatMan.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $** ..\..\common\mdk\$(OUTDIR)\mdk.lib ..\..\common\dsplib\$(OUTDIR)\dsplib.lib
	
"$(OUTDIR)\FSM PhatMan.prs": FSM_PhatMan.prs
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	copy $** $@
