!INCLUDE ..\..\..\common.nmake

CFLAGS = $(CFLAGS) /DNOMINMAX 

all: "$(OUTDIR)\SurfsDSPLib.lib"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\SurfsDSPLib.lib": $(OUTDIR)\SRF_2PFilter.obj $(OUTDIR)\SRF_Amp.obj $(OUTDIR)\SRF_AutoGain.obj $(OUTDIR)\SRF_DSP.obj $(OUTDIR)\SRF_Resampler.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	lib /OUT:$@ $**
