!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS) /DNOMINMAX /D_USE_MATH_DEFINES

all: "$(OUTDIR)\FSM WahPro2.dll"

clean:
	if exist $(OUTDIR) del $(OUTDIR)\*.* /q

install:
	@if not exist "$(INSTALLDIR_EFX)" mkdir "$(INSTALLDIR_EFX)"
	copy "$(OUTDIR)\FSM WahPro2.dll" "$(INSTALLDIR_EFX)" /y

"$(OUTDIR)\FSM WahPro2.dll": $(OUTDIR)\WahPro2.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $**
