!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS) /DNOMINMAX /D_USE_MATH_DEFINES

all: "$(OUTDIR)\FSM WahPro2.dll"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\FSM WahPro2.dll": $(OUTDIR)\WahPro2.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $**
