!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS) 

all: "$(OUTDIR)\dsplib.dll"

clean:
	if exist $(OUTDIR) del $(OUTDIR)\*.* /q

"$(OUTDIR)\dsplib.dll": $(OUTDIR)\dsplib.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $**
