!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS) /DNOMINMAX /D_USE_MATH_DEFINES

all: "$(OUTDIR)\FSM WahManPro.dll"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\FSM WahManPro.dll": $(OUTDIR)\WahManPro.obj
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $**
