!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS)

all: "$(OUTDIR)\Oomek Masterizer.dll"

clean:
	if exist $(OUTDIR) del $(OUTDIR)\*.* /q

install:
	@if not exist "$(INSTALLDIR_EFX)" mkdir "$(INSTALLDIR_EFX)"
	copy "$(OUTDIR)\Oomek Masterizer.dll" "$(INSTALLDIR_EFX)" /y

"$(OUTDIR)\Oomek Masterizer.dll": $(OUTDIR)\masterizer.obj 
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $** ..\..\common\mdk\$(OUTDIR)\mdk.lib ..\..\common\dsplib\$(OUTDIR)\dsplib.lib

