!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS)

all: "$(OUTDIR)\Oomek Masterizer.dll"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\Oomek Masterizer.dll": $(OUTDIR)\masterizer.obj 
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $** ..\..\common\mdk\$(OUTDIR)\mdk.lib ..\..\common\dsplib\$(OUTDIR)\dsplib.lib

