!INCLUDE ..\..\common.nmake

CFLAGS = $(CFLAGS)

all: "$(OUTDIR)\Oomek Aggressor 303.dll"

clean:
	del $(OUTDIR)\*.* /q

"$(OUTDIR)\Oomek Aggressor 303.dll": $(OUTDIR)\303.obj 
	if not exist $(OUTDIR) mkdir $(OUTDIR)
	cl $(LINKFLAGS) /Fe$@ $** user32.lib ..\..\common\mdk\$(OUTDIR)\mdk.lib ..\..\common\dsplib\$(OUTDIR)\dsplib.lib
